- hosts: localhost
  connection: local
  gather_facts: no
  vars:
      project: devops2021gcp
      auth_kind: serviceaccount
      gcp_cred_file: ~/.gcp/credentials.json
      zone: "europe-west2-c"
      region: "europe-west2"
      gcp_cred_kind: serviceaccount
  tasks:
    - block:
        - name: create a vpc
          google.cloud.gcp_compute_network:
            name: example-vpc
            auto_create_subnetworks: 'false'
            project: "{{ project }}"
            auth_kind: "{{ gcp_cred_kind }}"
            service_account_file: "{{ gcp_cred_file }}"
            state: present
          register: network

        - name: create a subnetwork
          google.cloud.gcp_compute_subnetwork:
            name: example-subnet
            region: "{{ region }}"
            network: "{{ network }}"
            ip_cidr_range: 10.0.0.0/24
            project: "{{ project }}"
            auth_kind: "{{ gcp_cred_kind }}"
            service_account_file: "{{ gcp_cred_file }}"
            state: present
          register: subnetwork

        - name: create a gcp instance
          google.cloud.gcp_compute_instance:
            name: exampleserver
            zone: "{{ zone }}"
            auth_kind: "{{ gcp_cred_kind }}"
            service_account_file: "{{ gcp_cred_file }}"
            project: "{{ project }}"
            machine_type: e2-medium
            network_interfaces:
              - subnetwork: "{{ subnetwork }}"
            disks:
             - initialize_params:
                 source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20211021 
               boot: 'true'
      when: playbook_action == 'create'
    - block:
        - google.cloud.gcp_compute_instance:
            name: exampleserver
            zone: "{{ zone }}"
            auth_kind: "{{ gcp_cred_kind }}"
            service_account_file: "{{ gcp_cred_file }}"
            project: "{{ project }}"
            machine_type: e2-medium
            state: absent
        - google.cloud.gcp_compute_subnetwork:
            name: example-subnet
            region: "{{ region }}"
            project: "{{ project }}"
            network: "{{ network }}"
            ip_cidr_range: 10.0.0.0/24
            auth_kind: "{{ gcp_cred_kind }}"
            service_account_file: "{{ gcp_cred_file }}"
            state: absent
        - google.cloud.gcp_compute_network:
            name: example-vpc
            project: "{{ project }}"
            auth_kind: "{{ gcp_cred_kind }}"
            service_account_file: "{{ gcp_cred_file }}"
            state: absent
      when: playbook_action == 'destroy'
      